# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ini-parser

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Install golint
      run: |
        go install golang.org/x/lint/golint@latest
        export PATH=$PATH:$(go env GOPATH)/bin

    - name: Run gofmt to check code format
      run: |
        go version
        gofmt -l .
      continue-on-error: true

    - name: Check for unformatted code
      if: failure()
      run: |
        echo "The following files are not formatted correctly:"
        gofmt -l .
        exit 1

    - name: Run golint
      run: |
        golint ./...
      continue-on-error: true

    - name: Check for linting issues
      if: failure()
      run: |
        echo "Linting issues found:"
        golint ./...
        exit 1

    - name: Run tests
      run: |
        go test ./...

    - name: Build the project
      run: |
        go build -v ./...